resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 4
      minimumNumberOfCalls: 4
      failureRateThreshold: 50
  instances:
    hoge:
      baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
